#!/usr/bin/env python
from feemodel.txmempool import TxMempool
from time import sleep

mempool = TxMempool()
mempool.start()

try:
    while(True):
        sleep(60)
finally:
    mempool.stop()
    mempool.join()
    print("Exiting program.")